version: "3.8"

services:
  n8n-main:
    image: n8nio/n8n:latest
    command: "start"
    ports:
      - "127.0.0.1:5678:5678"
    env_file: .env
    environment:
      - N8N_CUSTOM_EXTENSIONS=/home/node/custom-nodes
    volumes:
      - ./data:/home/node/.n8n
      - ./custom-nodes:/home/node/custom-nodes
      - ./ssl/rds-ca.pem:/home/node/.n8n/rds-ca.pem:ro
      - ./backup:/git
    container_name: n8n-main

  n8n-worker:
    image: n8nio/n8n:latest
    command: "worker"
    env_file: .env
    environment:
      - N8N_CUSTOM_EXTENSIONS=/home/node/custom-nodes
    volumes:
      - ./data:/home/node/.n8n
      - ./custom-nodes:/home/node/custom-nodes
      - ./ssl/rds-ca.pem:/home/no