version: '3.8'
networks:
  raelflow_net:
    external: true

services:
  openproject_db:
    image: postgres:14
    environment:
      POSTGRES_USER: openproject
      POSTGRES_PASSWORD: S3nh4OpenPr0j!
      POSTGRES_DB: openproject
    volumes:
      - ./data/openproject_db:/var/lib/postgresql/data
    networks:
      - raelflow_net

  openproject:
    build:
      context: ./services/openproject
    env_file:
      - env/openproject.env
    depends_on:
      - openproject_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openproject.rule=PathPrefix(`/openproject`)"
      - "traefik.http.services.openproject.loadbalancer.server.port=8080"
    volumes:
      - ./data/openproject_assets:/var/openproject/assets
    networks:
      - raelflow_net

  calendar:
    build:
      context: ./services/calendar
    env_file:
      - env/baikal.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calendar.rule=PathPrefix(`/calendar`)"
      - "traefik.http.services.calendar.loadbalancer.server.port=80"
    volumes:
      - ./data/baikal:/var/www/html/Specific
    networks:
      - raelflow_net
